version: '3.9'

services:

  core_php:
    build: .
    image: ggfable/core_php:v1
    container_name: core_php
    restart: unless-stopped
    working_dir: /var/www/core
    command: sh -c "composer install && php artisan storage:link && chmod o+w ./storage/ -R && npm install --location=global svgo && php-fpm"
    volumes:
      - ./app:/var/www/core
      - ./php-conf/.env:/var/www/core/.env
      - ./php-conf/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - nginx_network
    depends_on:
      - core_pgsql

  core_nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: ggfable/core_nginx:v1
    container_name: core_nginx
    restart: unless-stopped
    working_dir: /var/www/core
    ports:
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./app:/var/www/core
      - ./php-conf/.env:/var/www/core/.env
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    networks:
      - nginx_network
    depends_on:
      - core_php

  core_pgsql:
    build:
      context: .
      dockerfile: ./db-conf/Dockerfile
    image: ggfable/core_pgsql:v1
    container_name: core_pgsql
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_DB: "core_db"
      POSTGRES_USER: "core_usr"
      POSTGRES_PASSWORD: "Te0AsCLcYs_wEv_dAS2_sd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
      # - ./init:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U core_usr -d core_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks: 
      - nginx_network
